server:
  port: 8081

spring:
  application:
    name: LOVABLE
  datasource:
    url: jdbc:postgresql://localhost:5433/lovable_clone_db
    username: postgres
    password: khushi
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
